ssh_authorized_keys:
  - github:maddestructor
hostname: Kenobi
# init_cmd:
# - "echo hello, init command"
boot_cmd:
- "echo America/Montreal > /etc/timezone"
# run_cmd:
# - "echo hello, run command"

k3os:
  data_sources:
    - cdrom
  modules:
    - kvm
    - nvme
  sysctl:
    kernel.printk: "4 4 1 7"
    kernel.kptr_restrict: "1"
  dns_nameservers:
    - 192.168.1.1
    - 1.1.1.1
    - 1.0.0.1
  ntp_servers:
    - 0.ca.pool.ntp.org
    - 1.ca.pool.ntp.org
    - 2.ca.pool.ntp.org
    - 3.ca.pool.ntp.org
  password: "$6$QQHFGMms$g4zU8dHTq5GIo060ugZYyIDMkMB81GR.ueeYD1RFrh86Ygx4pzuWASjrCoTJDS5aac2N7o99EhglfqWHGBJ7f."
  # server_url: https://someserver:6443
  # token: TOKEN_VALUE
  labels:
    load-type: services
    node-type: high-power
  k3s_args:
    - server

write_files:
  - path: /var/lib/connman/default.config
    content: |-
      [service_eth0]
      Type=ethernet
      IPv4=192.168.1.220/255.255.192.0/192.168.1.1
      IPv6=off
      Nameservers=192.168.1.1/1.1.1.1/1.0.0.1
  - path: /etc/conf.d/qemu-guest-agent
    content: |-
      GA_PATH=/dev/vport2p1
    owner: root
    permissions: '0644'
  - encoding: b64
    content: 'VFppZjIAAAAAAAAAAAAAAAAAAAAAAAAFAAAABQAAAAAAAADpAAAABQAAABSAAAAAnriTcJ+662Cg
hy7IoZqxQKKUBvCjValApIZd8KUoeGCmZj/wpwxO4KhGIfCo7DDgqhzJcKrVTWCr/KtwrLUvYK3c
jXCulRFgr7xvcLB+LeCxnFFwsmdKYLN8M3C0RyxgtVwVcLYnDmC3O/dwuAbwYLklE/C55tJguwT1
8LvP7uC85Nfwva/Q4L7EufC/j7LgwKSb8MFvlODChH3ww0924MRkX/DFL1jgxk18cMcPOuDILV5w
y4jwcNIj9HDSYPvg03Xk8NRA3eDVVarQ1iCjwNc1jNDYAIXA2RVu0NozdkDa/qdw3BN0YNzeiXDd
qYJg3r5rcN+JZGDgnk1w4WlGYOJ+L3DjSShg5F4RcOUpCmDmRy3w5xIm4OgnD/DpFvLg6gbx8Or2
1ODr5tPw7Na24O3GtfDuv9Ng76/ScPCftWDxj7Rw8n+XYPNvlnD0X3lg9U94cPY/W2D3L1pw+Ch3
4PkPPHD6CFng+vhY8PvoO+D82Drw/cgd4P64HPD/p//gAJf+8AGH4eACd+DwA3D+YARg/XAFUOBg
BkDfcAcwwmAIIMFwCRCkYAoAo3AK8IZgC+CFcAzZouANwGdwDrmE4A+pg/AQmWbgEYll8BJ5SOAT
aUfwFFkq4BVJKfAWOQzgFykL8BgiKWAZCO3wGgILYBryCnAb4e1gHNHscB3Bz2Aesc5wH6GxYCB2
APAhgZNgIlXi8CNqr+AkNcTwJUqR4CYVpvAnKnPgJ/7DcCkKVeAp3qVwKuo34Cu+h3As01RgLZ5p
cC6zNmAvfktwMJMYYDFnZ/AycvpgM0dJ8DRS3GA1JyvwNjK+YDcHDfA4G9rgOObv8Dn7vOA6xtHw
O9ue4Dyv7nA9u4DgPo/QcD+bYuBAb7JwQYR/YEJPlHBDZGFgRC92cEVEQ2BF86jwRy1f4EfTivBJ
DUHgSbNs8ErtI+BLnIlwTNZAYE18a3BOtiJgT1xNcFCWBGBRPC9wUnXmYFMcEXBUVchgVPvzcFY1
qmBW5Q/wWB7G4FjE8fBZ/qjgWqTT8FveiuBchLXwXb5s4F5kl/Bfnk7gYE20cGGHa2BiLZZwY2dN
YGQNeHBlRy9gZe1acGcnEWBnzTxwaQbzYGmtHnBq5tVga5Y68GzP8eBtdhzwbq/T4G9V/vBwj7Xg
cTXg8HJvl+BzFcLwdE954HT+33B2OJZgdt7BcHgYeGB4vqNwefhaYHqehXB72DxgfH5ncH24HmB+
Xklwf5gAYAIBAgECAQIBAgECAQIBAgECAQIBAgECAQIBAgECAQIBAgECAQIBAgECAQIBAgEDBAIB
AgECAQIBAgECAQIBAgECAQIBAgECAQIBAgECAQIBAgECAQIBAgECAQIBAgECAQIBAgECAQIBAgEC
AQIBAgECAQIBAgECAQIBAgECAQIBAgECAQIBAgECAQIBAgECAQIBAgECAQIBAgECAQIBAgECAQIB
AgECAQIBAgECAQIBAgECAQIBAgECAQIBAgECAQIBAgECAQIBAgECAQIBAgECAQIBAgECAQIBAgEC
AQIBAgECAQIBAgEC//+1lAAA///HwAEE//+5sAAI///HwAEM///HwAEQTE1UAEVEVABFU1QARVdU
AEVQVAAAAAAAAQAAAAABVFppZjIAAAAAAAAAAAAAAAAAAAAAAAAFAAAABQAAAAAAAADqAAAABQAA
ABT4AAAAAAAAAP////9y7njs/////564k3D/////n7rrYP////+ghy7I/////6GasUD/////opQG
8P////+jValA/////6SGXfD/////pSh4YP////+mZj/w/////6cMTuD/////qEYh8P////+o7DDg
/////6ocyXD/////qtVNYP////+r/Ktw/////6y1L2D/////rdyNcP////+ulRFg/////6+8b3D/
////sH4t4P////+xnFFw/////7JnSmD/////s3wzcP////+0Ryxg/////7VcFXD/////ticOYP//
//+3O/dw/////7gG8GD/////uSUT8P////+55tJg/////7sE9fD/////u8/u4P////+85Nfw////
/72v0OD/////vsS58P////+/j7Lg/////8Ckm/D/////wW+U4P/////ChH3w/////8NPduD/////
xGRf8P/////FL1jg/////8ZNfHD/////xw864P/////ILV5w/////8uI8HD/////0iP0cP/////S
YPvg/////9N15PD/////1EDd4P/////VVarQ/////9Ygo8D/////1zWM0P/////YAIXA/////9kV
btD/////2jN2QP/////a/qdw/////9wTdGD/////3N6JcP/////dqYJg/////96+a3D/////34lk
YP/////gnk1w/////+FpRmD/////4n4vcP/////jSShg/////+ReEXD/////5SkKYP/////mRy3w
/////+cSJuD/////6CcP8P/////pFvLg/////+oG8fD/////6vbU4P/////r5tPw/////+zWtuD/
////7ca18P/////uv9Ng/////++v0nD/////8J+1YP/////xj7Rw//////J/l2D/////82+WcP//
///0X3lg//////VPeHD/////9j9bYP/////3L1pw//////god+D/////+Q88cP/////6CFng////
//r4WPD/////++g74P/////82Drw//////3IHeD//////rgc8P//////p//gAAAAAACX/vAAAAAA
AYfh4AAAAAACd+DwAAAAAANw/mAAAAAABGD9cAAAAAAFUOBgAAAAAAZA33AAAAAABzDCYAAAAAAI
IMFwAAAAAAkQpGAAAAAACgCjcAAAAAAK8IZgAAAAAAvghXAAAAAADNmi4AAAAAANwGdwAAAAAA65
hOAAAAAAD6mD8AAAAAAQmWbgAAAAABGJZfAAAAAAEnlI4AAAAAATaUfwAAAAABRZKuAAAAAAFUkp
8AAAAAAWOQzgAAAAABcpC/AAAAAAGCIpYAAAAAAZCO3wAAAAABoCC2AAAAAAGvIKcAAAAAAb4e1g
AAAAABzR7HAAAAAAHcHPYAAAAAAesc5wAAAAAB+hsWAAAAAAIHYA8AAAAAAhgZNgAAAAACJV4vAA
AAAAI2qv4AAAAAAkNcTwAAAAACVKkeAAAAAAJhWm8AAAAAAnKnPgAAAAACf+w3AAAAAAKQpV4AAA
AAAp3qVwAAAAACrqN+AAAAAAK76HcAAAAAAs01RgAAAAAC2eaXAAAAAALrM2YAAAAAAvfktwAAAA
ADCTGGAAAAAAMWdn8AAAAAAycvpgAAAAADNHSfAAAAAANFLcYAAAAAA1JyvwAAAAADYyvmAAAAAA
NwcN8AAAAAA4G9rgAAAAADjm7/AAAAAAOfu84AAAAAA6xtHwAAAAADvbnuAAAAAAPK/ucAAAAAA9
u4DgAAAAAD6P0HAAAAAAP5ti4AAAAABAb7JwAAAAAEGEf2AAAAAAQk+UcAAAAABDZGFgAAAAAEQv
dnAAAAAARURDYAAAAABF86jwAAAAAEctX+AAAAAAR9OK8AAAAABJDUHgAAAAAEmzbPAAAAAASu0j
4AAAAABLnIlwAAAAAEzWQGAAAAAATXxrcAAAAABOtiJgAAAAAE9cTXAAAAAAUJYEYAAAAABRPC9w
AAAAAFJ15mAAAAAAUxwRcAAAAABUVchgAAAAAFT783AAAAAAVjWqYAAAAABW5Q/wAAAAAFgexuAA
AAAAWMTx8AAAAABZ/qjgAAAAAFqk0/AAAAAAW96K4AAAAABchLXwAAAAAF2+bOAAAAAAXmSX8AAA
AABfnk7gAAAAAGBNtHAAAAAAYYdrYAAAAABiLZZwAAAAAGNnTWAAAAAAZA14cAAAAABlRy9gAAAA
AGXtWnAAAAAAZycRYAAAAABnzTxwAAAAAGkG82AAAAAAaa0ecAAAAABq5tVgAAAAAGuWOvAAAAAA
bM/x4AAAAABtdhzwAAAAAG6v0+AAAAAAb1X+8AAAAABwj7XgAAAAAHE14PAAAAAAcm+X4AAAAABz
FcLwAAAAAHRPeeAAAAAAdP7fcAAAAAB2OJZgAAAAAHbewXAAAAAAeBh4YAAAAAB4vqNwAAAAAHn4
WmAAAAAAep6FcAAAAAB72DxgAAAAAHx+Z3AAAAAAfbgeYAAAAAB+XklwAAAAAH+YAGAAAgECAQIB
AgECAQIBAgECAQIBAgECAQIBAgECAQIBAgECAQIBAgECAQIBAgECAQMEAgECAQIBAgECAQIBAgEC
AQIBAgECAQIBAgECAQIBAgECAQIBAgECAQIBAgECAQIBAgECAQIBAgECAQIBAgECAQIBAgECAQIB
AgECAQIBAgECAQIBAgECAQIBAgECAQIBAgECAQIBAgECAQIBAgECAQIBAgECAQIBAgECAQIBAgEC
AQIBAgECAQIBAgECAQIBAgECAQIBAgECAQIBAgECAQIBAgECAQIBAgECAQIBAgECAQIBAgECAQL/
/7WUAAD//8fAAQT//7mwAAj//8fAAQz//8fAARBMTVQARURUAEVTVABFV1QARVBUAAAAAAABAAAA
AAEKRVNUNUVEVCxNMy4yLjAsTTExLjEuMAo='
    owner: root:root
    path: /etc/localtime
    permissions: '0644'